[package]
name = "bootloader"
version = "0.1.0"
authors = ["Luis Hebendanz <luis.nixos@gmail.com>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
llvm-tools = { version = "0.1" }

[features]
binary = []

[package.metadata.bootloader]
target = "i686-unknown-linux-gnu.json"
build-std = "core"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = false
debug = true
