[package]
name = "svm_kernel"
version = "0.1.0"
authors = ["Luis Hebendanz <luis.nixos@gmail.com>"]
edition = "2018"


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
# lto = "fat"
opt-level = 3
debug=true
codegen-units=1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bootloader = "0.9.11"
uart_16550 = "0.2.10"
spin = "0.6.0"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

# cargo run command options
[package.metadata.bootimage]
run-command = ["qemu-kvm","-cpu", "qemu64,+svm,vendor=AuthenticAMD", "-drive", "format=raw,file={}", "-nographic"]
