[package]
name = "svm_kernel"
version = "0.1.0"
authors = ["Luis Hebendanz <luis.nixos@gmail.com>"]
edition = "2018"

[profile.dev]

[profile.release]
panic = "abort"
lto = "fat"
opt-level = 3
debug=true
codegen-units=1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bootloader = "0.9.11"
log = "0.4.11"
pic8259_simple = "0.2.0"
uart_16550 = "0.2.10"
spin = "0.6.0"
x86_64 = "0.12.2"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

# cargo run command options
[package.metadata.bootimage]
# run-command = ["qemu-kvm","-cpu", "qemu64,+svm,vendor=AuthenticAMD", "-drive", "format=raw,file={}", "-serial", "stdio", "-display", "none"]
run-command = ["qemu-kvm","-cpu", "qemu64,+svm,vendor=AuthenticAMD", "-drive", "format=raw,file={}",]
# build-command = ["build", "--release"]
build-command = ["build"]
test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04"]
test-success-exit-code = 33         # (0x10 << 1) | 1
test-timeout = 300          # (in seconds)
